pull_request_rules:
  - name: merge when green
    conditions:
      - "label=⤴️PR: Merge When Green"
      - "label!=⤴️PR: Work In Progress"
      - "label!=⤴️PR: Can't Be Automerged"
      - status-success=AccessLint
      - status-success=CodeFactor
      - status-success=build (12.x)
      - status-success=task-list-completed
      - status-success=pullapprove
    actions:
      merge:
        method: merge
  - name: label style updates
    conditions:
      - author=restyled-io
    actions:
      label:
        add:
          - "⤴️PR: Style Update"
          - "⤴️PR: Enhancement"
          - "⤴️PR: Merge When Green"
