version: 3

pullapprove_conditions:
- "base.ref == 'master'"
  unmet_status: success
  explanation: "Minion3665 wishes you luck. This pr will not need reviews to pass ðŸ˜Š"
- condition: "'â¤´ï¸PR: Work In Progress' not in labels"
  unmet_status: pending
  explanation: "Work in progress"
- condition: "'task-list-completed' in statuses.successful"
  unmet_status: pending
  explanation: "Work in progress"
- condition: "'restyled' in statuses.successful" and"
  unmet_status: pending
  explanation: "Your style must fit before reviewing starts"
- condition: "'AnyLint' in statuses.successful"
  unmet_status: pending
  explanation: "AnyLint must succeed before reviewing starts"
- condition: "'Travis CI - Pull Request' in statuses.successful"
  unmet_status: pending
  explanation: "The Travis-CI Build must pass before reviewing starts"

groups:
  protected:
    conditions:
    - >
      '*.md' in files or
      '*.html' in files or
      '*.yml' in files or
      '*.yaml' in files or
      '*.json' in files or
      'CNAME' in files or
      'config.js' in files or
      'index.js' in files or
      'webpack.config.js' in files or
      '*favicon*' in files
    reviewers:
      users:
      - Minion3665
    reviews:
      required: 1
      request: 1
